version: '3'
services: 

  # database:
  #   build: ./database
  #   volumes:
  #     - database-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/code:/var/opt/fisheye

volumes:
  database-data: